// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: upgrade.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const upgradeToRed = `-- name: UpgradeToRed :one
UPDATE users
SET is_chirpy_red = TRUE, updated_at = NOW()
WHERE id = $1
RETURNING id, is_chirpy_red, updated_at
`

type UpgradeToRedRow struct {
	ID          uuid.UUID
	IsChirpyRed bool
	UpdatedAt   time.Time
}

func (q *Queries) UpgradeToRed(ctx context.Context, id uuid.UUID) (UpgradeToRedRow, error) {
	row := q.db.QueryRowContext(ctx, upgradeToRed, id)
	var i UpgradeToRedRow
	err := row.Scan(&i.ID, &i.IsChirpyRed, &i.UpdatedAt)
	return i, err
}
